version: '3.9'
services:
  backend:
    restart: always
    image: ezow0rm/sotvetis-backend:latest
    ports:
      - '8080:8080'
    volumes:
      - users:/app/users
    links:
      - mysql
    depends_on:
      - check-db-started

  frontend:
    image: ezow0rm/sotvetis-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
  
  # Wait for MySQL to be joinable.
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - mysql
    links:
      - mysql
    command: 'dockerize -wait=tcp://mysql:3306'

  mysql:
    image: mysql:latest
    ports:
      - '4000:3306'
    expose:
      - '3306'
    volumes:
      - sql_data_v0.2:/var/sql_data
    environment:
      - MYSQL_DATABASE=taskdb
      - MYSQL_ROOT_PASSWORD=1234

  shell:
    image: alpine
    depends_on:
      - backend
      - frontend
      - check-db-started
    command: sh -c "sleep 3 && echo -e '============== Сервер SOTVETIS запущен! Ссылка - http://localhost:80 =============='"

volumes:
  sql_data_v0.2:
  users:
