version: '3.9'
services:
  backend:
    restart: always
    image: rakkateichou/sotvetis-backend:latest
    ports:
      - '8080:8080'
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: rakkateichou/sotvetis-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - '4000:3306'
    expose:
      - '3306'
    volumes:
      - sql_data:/var/sql_data
    environment:
      - MYSQL_DATABASE=taskdb
      - MYSQL_ROOT_PASSWORD=1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 80

  finally:
    image: alpine
    depends_on:
      - backend
      - frontend
      - mysql
    command: sh -c "sleep 1 && echo '======================== Сервер SOTVETIS запущен! ========================'"

volumes:
  sql_data:
